import Head from 'next/head'
import { useState , useEffect } from 'react';
import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.css'
import styles from '../../styles/brain/sensor.module.scss'
import Link from "next/link";
import BrainSensor from '../../components/brainsensor';

export default function Sensor() {
  const [message, setMessage] = useState(null);
  return (
    <div className={styles.container}>
      <Head>        
        <title>Install</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='prev_page'>
          <Link href="/brain/install"> 
            <Image
                src="/images/prev.png"
                alt="Women"
                // layout="fill"
                // objectFit="cover"
                width={196}
                height={196}
            />
            </Link>
      </div>{/* prev_page */}
      <div>
        <BrainSensor />
      </div>
    </div>
  )
}